In [12]:
import numpy as np
import torch
import snntorch as snn
import snntorch.functional as SF
import snntorch.spikegen as spikegen
import numpy as np

In [6]:
np.max(a=[0,0.5])

0.5

In [13]:
def generate_spike_trains(observation, num_steps, threshold, shift):
    """
    Generate spike trains from a single observation using a fixed global threshold.

    Parameters:
    - observation: A tensor representing the observation ([observation_dim]).
    - num_steps: The number of timesteps for the spike train.
    - threshold: A single global threshold value to be used for normalization.

    Returns:
    - spike_trains: Tensor of spike trains.
    """

    # Normalize and clip observation
    shifted_obs = np.add(observation, shift)

    # torch version
    # shifted_obs = observation + shift

    normalized_obs = shifted_obs / (threshold + 1e-6)  # Avoid division by zero

    normalized_obs /= 2

    normalized_obs = normalized_obs.clamp(0, 1)  # Clip values to be within [0, 1]

    # Generate spike trains
    spike_trains = spikegen.rate(normalized_obs, num_steps=num_steps)

    # torch version
    # return spike_trains

    return spike_trains.numpy()


In [25]:
obs_dim = 5
timesteps = 10

obs = np.random.uniform(-1, 1, size=(obs_dim,)) * 3
print(obs)



[ 1.83423452  1.44409435  1.72015557 -0.55664161 -1.60466882]


In [26]:
threshold = torch.full((obs_dim,), 1.0)
shift = torch.full((obs_dim,), -1.0)

In [27]:
trains = generate_spike_trains(obs, timesteps, threshold, shift)
print(trains)

[[1. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 0. 1. 0. 0.]
 [1. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [ ]:
before the first update : 0.5
after the first update : 

SyntaxError: invalid syntax (1562935752.py, line 1)